In [1]:
import pandas as pd

In [2]:
import numpy as np

# Mimicdata to gform

In [3]:
mimicdata = pd.read_parquet("gdata.parquet")

In [4]:
mimicdata = mimicdata.loc[~mimicdata.groupby('admission_id')['A'].transform('max').eq(0)].copy()

In [5]:
mimicdata.admission_id.nunique()

76380

In [6]:
mimicdata.groupby('admission_id')['Z'].max().mean()

0.13713013877978528

# Zdata

In [7]:
Zdata = pd.read_parquet("./fit_data_Z.parquet")

In [21]:
Zdata.admission_id.unique()

array(['mimic4-30000153', 'mimic4-30000213', 'mimic4-30000484', ...,
       'mimic4-39997710', 'mimic4-39997753', 'mimic4-39997955'],
      dtype=object)

In [22]:
Zdata.loc[Zdata.admission_id=="mimic4-30000153"]

,admission_id,tD,t_death,Z,weight,A,vent_mode__last__last_12h,cumavg_vent_mode__hours_since_last__last_12h,cumavg_pco2_arterial__mean__last_12h,cumavg_po2_arterial__mean__last_12h,...,cumavg_lactate__last__last_12h,cumavg_fluid_out_urine__mean__last_12h,cumavg_ureum__last__last_12h,cumavg_creatinine__last__last_12h,cumavg_arterial_blood_pressure_mean__mean__last_12h,cumavg_heart_rate__mean__last_12h,cumavg_hemoglobin__last__last_12h,cumavg_temperature__mean__last_12h,cumavg_activated_partial_thromboplastin_time__last__last_12h,cumavg_bicarbonate_arterial__last__last_12h
20948,mimic4-30000153,1,<NA>,0,180,1,unknown,6.983333,44.0,233.0,...,1.6,68.611111,14.28,141.440002,88.113556,106.746792,10.5,37.479166,44.099998,20.0

In [27]:
Zdata.loc[Zdata.admission_id=="mimic4-30000484"]

,admission_id,tD,t_death,Z,weight,A,vent_mode__last__last_12h,cumavg_vent_mode__hours_since_last__last_12h,cumavg_pco2_arterial__mean__last_12h,cumavg_po2_arterial__mean__last_12h,...,cumavg_lactate__last__last_12h,cumavg_fluid_out_urine__mean__last_12h,cumavg_ureum__last__last_12h,cumavg_creatinine__last__last_12h,cumavg_arterial_blood_pressure_mean__mean__last_12h,cumavg_heart_rate__mean__last_12h,cumavg_hemoglobin__last__last_12h,cumavg_temperature__mean__last_12h,cumavg_activated_partial_thromboplastin_time__last__last_12h,cumavg_bicarbonate_arterial__last__last_12h
0,mimic4-30000484,3,74,0,71,1,unknown,6.183056,59.0,21.0,...,1.6,80.444445,14.28,141.440002,72.663462,91.5625,10.5,36.184029,44.099998,20.0
10474,mimic4-30000484,3,74,1,1,1,unknown,6.183056,59.0,21.0,...,1.6,80.444445,14.28,141.440002,72.663462,91.5625,10.5,36.184029,44.099998,20.0

In [26]:
Zdata.loc[Zdata.Z==1]

,admission_id,tD,t_death,Z,weight,A,vent_mode__last__last_12h,cumavg_vent_mode__hours_since_last__last_12h,cumavg_pco2_arterial__mean__last_12h,cumavg_po2_arterial__mean__last_12h,...,cumavg_lactate__last__last_12h,cumavg_fluid_out_urine__mean__last_12h,cumavg_ureum__last__last_12h,cumavg_creatinine__last__last_12h,cumavg_arterial_blood_pressure_mean__mean__last_12h,cumavg_heart_rate__mean__last_12h,cumavg_hemoglobin__last__last_12h,cumavg_temperature__mean__last_12h,cumavg_activated_partial_thromboplastin_time__last__last_12h,cumavg_bicarbonate_arterial__last__last_12h
10474,mimic4-30000484,3,74,1,1,1,unknown,6.183056,59.000000,21.000000,...,1.6,80.444445,14.280000,141.440002,72.663462,91.562500,10.5,36.184029,44.099998,20.0
10475,mimic4-30000646,7,13,1,1,1,unknown,6.183056,30.000000,71.000000,...,4.9,185.714279,14.280000,141.440002,70.055985,94.755244,10.5,36.852548,44.099998,20.0
10476,mimic4-30004391,15,140,1,1,1,unknown,6.325000,26.218750,50.438823,...,4.9,79.007137,7.140000,97.240005,78.270432,103.861836,8.6,36.766205,44.099998,24.0
10477,mimic4-30007228,0,18,1,1,1,unknown,2.144444,39.833332,191.166672,...,1.6,128.888885,15.708000,150.280014,91.230766,103.800003,11.3,36.759258,82.000000,26.0
10478,mimic4-30011071,4,54,1,1,1,unknown,3.762222,37.000000,191.000000,...,5.3,79.500000,3.927000,61.880001,102.057576,106.684937,11.1,36.666669,26.000000,30.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20943,mimic4-39993265,3,14,1,1,1,unknown,0.309722,42.000000,47.000000,...,2.3,105.000000,7.140000,70.720001,71.148809,75.043451,9.1,36.966435,26.000000,25.0
20944,mimic4-39993425,3,5,1,1,1,unknown,0.309722,37.500000,30.000000,...,2.3,105.000000,14.993999,70.720001,79.807692,93.586538,9.1,35.861112,29.700001,46.0
20945,mimic4-39995141,0,22,1,1,1,unknown,8.316944,34.333332,59.666668,...,1.1,58.571430,8.210999,61.880001,97.416664,91.500000,8.3,36.629631,29.700001,23.0
20946,mimic4-39995630,0,84,1,1,1,unknown,2.997778,38.000000,33.000000,...,1.1,34.500000,8.210999,61.880001,75.777779,87.500000,8.3,36.916672,29.700001,23.0
20947,mimic4-39996044,12,150,1,1,1,unknown,1.783333,39.415385,77.543589,...,1.1,144.926989,8.210999,61.880001,79.819835,105.494473,8.3,36.808406,29.700001,23.0

In [8]:
Zdata.admission_id.nunique()

76380

In [19]:
Zdata.groupby('admission_id')['Z'].max().mean()

0.13713013877978528

# Inspecting differences

In [10]:
adm_A = set(mimicdata.loc[mimicdata["A"].eq(1), "admission_id"].unique())
adm_Z = set(Zdata["admission_id"].unique())

missing = sorted(adm_A - adm_Z)
extra   = sorted(adm_Z - adm_A)

len(missing), missing[:20], len(extra), extra[:20]

(0, [], 0, [])

In [11]:
len(adm_A)

76380

In [12]:
len(adm_Z)

76380

In [13]:
mZ = mimicdata.groupby("admission_id")["Z"].max()
zZ = Zdata.groupby("admission_id")["Z"].max()

diff_ids = mZ.index[(mZ == 1) & (zZ == 0)]
len(diff_ids), diff_ids[:10]

(0, Index([], dtype='object', name='admission_id'))

In [14]:
disc = (mimicdata.loc[mimicdata["A"] == 1, ["admission_id", "t0", "death_time_from_intime"]]
        .sort_values(["admission_id","t0"])
        .drop_duplicates("admission_id", keep="first")
        .set_index("admission_id"))

pd.Series({
    "diff_count": len(diff_ids),
    "death_td_missing_on_discharge_among_diff": disc.loc[diff_ids, "death_time_from_intime"].isna().mean(),
    "death_td_missing_on_discharge_overall": disc["death_time_from_intime"].isna().mean(),
})

diff_count                                  0.000000
death_td_missing_on_discharge_among_diff         NaN
death_td_missing_on_discharge_overall       0.652003
dtype: float64

In [15]:
diff_df = mimicdata.loc[mimicdata["admission_id"].isin(diff_ids),
                        ["admission_id","death_time_from_intime"]].drop_duplicates()

hours = diff_df["death_time_from_intime"] / pd.Timedelta(hours=1)

# check how close they are to multiples of 12
remainder = hours % 12

print("Near 0h remainder (<1e-6):",
      (remainder.abs() < 1e-6).mean())

Near 0h remainder (<1e-6): nan